"""create hashtag/post relationship

Revision ID: 72b1520cdcc3
Revises: ceea027c74d4
Create Date: 2022-07-29 18:31:51.392294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72b1520cdcc3'
down_revision = 'ceea027c74d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('hashtagId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hashtagId'], ['hashtags.id'], ),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('postId', 'hashtagId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    # ### end Alembic commands ###
