"""updated name,profileImage,bio columns

Revision ID: d55b38ee039d
Revises: ffdc0a98111c
Create Date: 2022-07-21 11:29:04.618458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55b38ee039d'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=False))
    op.add_column('users', sa.Column('profileImage', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'profileImage')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
